- job:
    name: logstash-input-gitrepo_docker-build-node
    project-type: freestyle
    description: |
      Node is a base image which jenkins can run its job on.
    display-name: '[LIP-GitRepo] Docker build node image'
    concurrent: false
    node: lip-gitrepo_docker
    scm:
      - logstash-input-gitrepo
    builders:
      - shell:
          !include-raw ../scripts/merge.sh
      - shell: |
          set +x
          pushd "${WORKSPACE}/logstash-input-gitrepo_${BUILD_NUMBER}/docker/node"
          if [ $(git diff --stat "HEAD^" -- . | wc -l) -gt 0 ]; then
            echo "============================"
            echo "Docker - Building Node Image"
            echo "============================"
            docker build -t "lip_gitrepo/node_test" .
          else
            docker tag -f abraverm/jenkins:node lip_gitrepo/node_test
            echo "Nothing changed"
          fi
